import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    FileText,
    Sparkles,
    Download,
    Copy,
    Trash2,
    Layout,
    Type,
    Clock,
    CheckCircle,
    Loader2,
    FileCode,
    Languages
} from 'lucide-react';

const DocumentCreator = () => {
    const [isGenerating, setIsGenerating] = useState(false);
    const [docType, setDocType] = useState('Assignment');
    const [prompt, setPrompt] = useState('');
    const [generatedContent, setGeneratedContent] = useState('');

    const docTemplates = [
        { id: 'Assignment', icon: FileText, label: 'Assignment', color: 'text-blue-600', bg: 'bg-blue-50' },
        { id: 'Syllabus', icon: Layout, label: 'Syllabus', color: 'text-purple-600', bg: 'bg-purple-50' },
        { id: 'Notice', icon: Type, label: 'Notice', color: 'text-orange-600', bg: 'bg-orange-50' },
        { id: 'Notes', icon: FileCode, label: 'Study Notes', color: 'text-green-600', bg: 'bg-green-50' },
    ];

    const handleGenerate = () => {
        if (!prompt) return;
        setIsGenerating(true);

        // Mocking AI Generation
        setTimeout(() => {
            const content = `# ${docType}: ${prompt}\n\n` +
                `## Introduction\nThis document was automatically generated by the SmartCollege AI Assistant for the requested topic. It provides a structured overview and key points.\n\n` +
                `## Key Objectives\n1. Understand the core principles of ${prompt}.\n2. Analyze the historical context and modern applications.\n3. Evaluate the impact on current industry standards.\n\n` +
                `## Main Content\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.\n\n` +
                `## Conclusion\nIn summary, ${prompt} remains a critical area of study within the current curriculum.`;

            setGeneratedContent(content);
            setIsGenerating(false);
        }, 2000);
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(generatedContent);
        alert('Copied to clipboard!');
    };

    return (
        <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-black text-gray-900 tracking-tight flex items-center">
                        AI Document Creator <Sparkles className="ml-3 h-6 w-6 text-primary-500 animate-pulse" />
                    </h1>
                    <p className="text-gray-500 font-medium">Generate academic materials and official documents in seconds</p>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                {/* Configuration Panel */}
                <div className="space-y-6">
                    <div className="bg-white p-6 rounded-3xl border border-gray-200 shadow-xl shadow-gray-200/50">
                        <h2 className="text-sm font-black text-gray-400 uppercase tracking-widest mb-6 px-1">1. Choose Template</h2>
                        <div className="grid grid-cols-2 gap-3">
                            {docTemplates.map((tmpl) => (
                                <button
                                    key={tmpl.id}
                                    onClick={() => setDocType(tmpl.id)}
                                    className={`p-4 rounded-2xl border-2 transition-all flex flex-col items-center text-center gap-2 group ${docType === tmpl.id
                                        ? 'border-primary-600 bg-primary-50 shadow-inner'
                                        : 'border-transparent bg-gray-50 hover:bg-gray-100'
                                        }`}
                                >
                                    <div className={`p-2 rounded-xl ${tmpl.bg} ${tmpl.color} group-hover:scale-110 transition-transform`}>
                                        <tmpl.icon className="h-5 w-5" />
                                    </div>
                                    <span className={`text-xs font-bold ${docType === tmpl.id ? 'text-primary-700' : 'text-gray-600'}`}>
                                        {tmpl.label}
                                    </span>
                                </button>
                            ))}
                        </div>

                        <div className="mt-8 space-y-4">
                            <h2 className="text-sm font-black text-gray-400 uppercase tracking-widest px-1">2. Describe Content</h2>
                            <textarea
                                value={prompt}
                                onChange={(e) => setPrompt(e.target.value)}
                                placeholder="e.g. Introduction to Quantum Computing for Semester 4 Students..."
                                className="w-full h-40 p-4 bg-gray-50 border border-gray-200 rounded-2xl focus:bg-white focus:border-primary-500 focus:ring-4 focus:ring-primary-500/10 outline-none transition-all resize-none text-sm font-medium placeholder:text-slate-400"
                            />
                        </div>

                        <button
                            onClick={handleGenerate}
                            disabled={isGenerating || !prompt}
                            className="w-full mt-6 py-4 bg-primary-600 text-white font-black rounded-2xl shadow-xl shadow-primary-200 flex items-center justify-center hover:bg-primary-700 active:scale-[0.98] transition-all disabled:opacity-50"
                        >
                            {isGenerating ? (
                                <>
                                    <Loader2 className="h-5 w-5 mr-3 animate-spin" />
                                    GENEATING...
                                </>
                            ) : (
                                <>
                                    <Sparkles className="h-5 w-5 mr-3" />
                                    CREATE DOCUMENT
                                </>
                            )}
                        </button>
                    </div>

                    <div className="bg-gradient-to-br from-gray-900 to-slate-800 p-6 rounded-3xl text-white shadow-xl">
                        <div className="flex items-center gap-3 mb-4">
                            <Languages className="h-5 w-5 text-primary-400" />
                            <h3 className="font-bold">Multi-language Support</h3>
                        </div>
                        <p className="text-xs text-gray-400 leading-relaxed font-medium">
                            Generate documents in English, Spanish, French, or Hindi by simply specifying the language in your prompt.
                        </p>
                    </div>
                </div>

                {/* Preview Panel */}
                <div className="lg:col-span-2">
                    <div className="bg-white rounded-3xl border border-gray-200 shadow-xl shadow-gray-200/50 flex flex-col min-h-[600px] overflow-hidden">
                        <div className="p-6 border-b border-gray-50 flex items-center justify-between bg-gray-50/30">
                            <div className="flex items-center gap-2">
                                <div className="h-2 w-2 rounded-full bg-red-400"></div>
                                <div className="h-2 w-2 rounded-full bg-amber-400"></div>
                                <div className="h-2 w-2 rounded-full bg-green-400"></div>
                                <span className="ml-3 text-xs font-bold text-gray-400 uppercase tracking-widest italic flex items-center">
                                    {isGenerating ? 'AI is thinking...' : 'Live Preview'}
                                </span>
                            </div>

                            {generatedContent && (
                                <div className="flex gap-2">
                                    <button
                                        onClick={handleCopy}
                                        className="p-2 text-gray-400 hover:text-primary-600 hover:bg-primary-50 rounded-lg transition-all"
                                        title="Copy to Clipboard"
                                    >
                                        <Copy className="h-4 w-4" />
                                    </button>
                                    <button
                                        className="p-2 text-gray-400 hover:text-green-600 hover:bg-green-50 rounded-lg transition-all"
                                        title="Download PDF"
                                    >
                                        <Download className="h-4 w-4" />
                                    </button>
                                    <button
                                        onClick={() => setGeneratedContent('')}
                                        className="p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-all"
                                        title="Discard"
                                    >
                                        <Trash2 className="h-4 w-4" />
                                    </button>
                                </div>
                            )}
                        </div>

                        <div className="flex-1 p-8 overflow-y-auto">
                            <AnimatePresence mode="wait">
                                {isGenerating ? (
                                    <motion.div
                                        initial={{ opacity: 0 }}
                                        animate={{ opacity: 1 }}
                                        exit={{ opacity: 0 }}
                                        className="h-full flex flex-col items-center justify-center text-center space-y-4"
                                    >
                                        <div className="relative">
                                            <div className="h-16 w-16 border-4 border-primary-100 rounded-full"></div>
                                            <div className="h-16 w-16 border-4 border-t-primary-600 rounded-full animate-spin absolute top-0"></div>
                                        </div>
                                        <p className="text-gray-400 font-bold animate-pulse uppercase tracking-widest text-xs">Architecting your document...</p>
                                    </motion.div>
                                ) : generatedContent ? (
                                    <motion.div
                                        initial={{ opacity: 0, y: 10 }}
                                        animate={{ opacity: 1, y: 0 }}
                                        className="prose prose-slate max-w-none"
                                    >
                                        <pre className="whitespace-pre-wrap font-sans text-gray-700 leading-relaxed text-sm">
                                            {generatedContent}
                                        </pre>
                                    </motion.div>
                                ) : (
                                    <div className="h-full flex flex-col items-center justify-center text-center opacity-30 select-none">
                                        <FileText className="h-20 w-20 mb-4" />
                                        <p className="font-black text-2xl uppercase tracking-tighter">Enter a prompt to start</p>
                                        <p className="text-sm font-medium mt-2">The AI assistant will curate your content here</p>
                                    </div>
                                )}
                            </AnimatePresence>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default DocumentCreator;
